debug:
  enabled: false
hub:
  args:
    - dossier
    - --config
    - /usr/local/etc/jupyterhub/jupyterhub_config.py
  config:
    Authenticator:
      auto_login: false
    GenericOAuthenticator:
      claim_groups_key: tenants
      allowed_groups:
        - admin
      admin_groups:
        - admin
      client_id: jupyter
      client_secret: ******
      enable_auth_state: true
      oauth_callback_url: https://jupyter.test-odh.di.unito.it/hub/oauth_callback
      authorize_url: https://identity.test-odh.di.unito.it/auth/realms/opendeephealth/protocol/openid-connect/auth
      token_url: https://identity.test-odh.di.unito.it/auth/realms/opendeephealth/protocol/openid-connect/token
      userdata_url: https://identity.test-odh.di.unito.it/auth/realms/opendeephealth/protocol/openid-connect/userinfo
      login_service: keycloak
      username_key: email
    JupyterHub:
      authenticator_class: generic-oauth
  cookieSecret: ******
  db:
    password: ******
    type: postgres
    url: "postgresql+psycopg2://jhub@jhub-postgresql:5432/jhubdb"
  extraConfig:
    authenticatorConfig: c.JupyterHub.authenticator_class = 'dossier.auth.oauth.DossierOAuthenticator'
    spawnerConfig: |
      from dossier.spawners.kubespawner import DossierKubeSpawner
      c.JupyterHub.spawner_class = DossierKubeSpawner
      c.JupyterHub.hub_connect_url = f'http://{get_name("hub")}.{os.environ.get("POD_NAMESPACE", "default")}:{get_name_env("hub", "_SERVICE_PORT")}'
      c.KubeSpawner.enable_user_namespaces = True
  image:
    name: alphaunito/dossier
    pullPolicy: Always
    pullSecrets:
    - jupyter-harbor-image-puller
    tag: 0.0.1-alpha
  labels:
    jhub-postgresql-client: "true"
  networkPolicy:
    enabled: true
    interNamespaceAccessLabels: accept
proxy:
  chp:
    networkPolicy:
      enabled: true
      interNamespaceAccessLabels: accept
  secretToken: ******
  service:
    type: ClusterIP
scheduling:
  corePods:
    nodeAffinity:
      matchNodePurpose: require
  userPods:
    nodeAffinity:
      matchNodePurpose: require
  userScheduler:
    enabled: true
singleuser:
  cloudMetadata:
    blockWithIptables: false
  defaultUrl: "/tree/"
  extraEnv:
    JUPYTERHUB_SINGLEUSER_APP: notebook.notebookapp.NotebookApp
  extraAnnotations:
    seccomp.security.alpha.kubernetes.io/pod: runtime/default
    container.seccomp.security.alpha.kubernetes.io/notebook: runtime/default
  networkPolicy:
    enabled: true
    interNamespaceAccessLabels: accept
  startTimeout: 600